services:
  mysql:
    image: mysql:8.4
    container_name: devatlas-mysql
    environment:
      MYSQL_DATABASE: devatlas
      MYSQL_USER: devatlas_user
      MYSQL_PASSWORD: devatlas_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devatlas_data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: devatlas-redis
    ports:
      - "6379:6379"
    volumes:
      - devatlas_redis_data:/data

volumes:
  devatlas_data:
  devatlas_redis_data:
