spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:devatlas}?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=devatlas_user
spring.datasource.password=devatlas_password

spring.flyway.enabled=true